[phases.setup]
nixPkgs = ["python311", "gcc", "libmysqlclient"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120"
